<?php
declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \AthosCommerce\Feed\ViewModel\CartViewModel $viewModel */
/** @var \AthosCommerce\Feed\ViewModel\GlobalScriptViewModel $scriptModel */

$viewModel = $block->getData('cart_view_model');
$scriptModel = $block->getData('global_script_model');

if (!$scriptModel || !$viewModel || !$scriptModel->shouldRender()) {
    return;
}
$cartData = $viewModel->getCartPageData();
if (empty($cartData['products'])) {
    return;
}
?>

<script type="text/javascript" id="athoscommerce_tracking_cart_page">
    (function () {
        window.athos.tracker.events.cart = window.athos.tracker.events.cart || {};
        var cartPageData = <?= /* @noEscape */ $cartData['products'] ?? [] ?>;

        if (typeof window.athos.tracker.events.cart.add === 'function') {
            window.athos.tracker.events.cart.add({
                data: {
                    results: cartPageData.products,
                    cart: cartPageData.products
                }
            });
        }
    })();
</script>
