<?php
declare(strict_types=1);

use AthosCommerce\Feed\ViewModel\CartViewModel;
use AthosCommerce\Feed\ViewModel\Escaper;
use AthosCommerce\Feed\ViewModel\GlobalScriptViewModel;
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @var Template $block */
/** @var CartViewModel $cartViewModel */
/** @var GlobalScriptViewModel $globalScriptViewModel */
/** @var SecureHtmlRenderer $secureRenderer */
/** @var Escaper $escaperViewModel */

$cartViewModel = $block->getCartViewModel();
$globalScriptViewModel = $block->getGlobalScriptViewModel();
$escaperViewModel = $block->getEscaperViewModel();
$escaper = $escaperViewModel->getEscaper();

if (!$globalScriptViewModel || !$cartViewModel || !$globalScriptViewModel->shouldRender()) {
    return;
}
$cartPageData = $cartViewModel->getCartPageData();
if (empty($cartPageData)) {
    return;
}
?>
<?php
$scriptString = "
    (function () {
        window.athos.tracker.events.cart = window.athos.tracker.events.cart || {};
        var cartPageProducts = [];
         try {
             cartPageProducts = JSON.parse('{$escaper->escapeJs($cartPageData)}') || [];
         } catch (e) {
             cartPageProducts = [];
         }
         window.athos.tracker.events.cartPageProducts = cartPageProducts;

        if (typeof window.athos.tracker.events.cart.add === 'function') {
            window.athos.tracker.events.cart.add({
                data: {
                    results: cartPageProducts,
                    cart: cartPageProducts
                }
            });
        }
    })();
";
?>
<?= /* @noEscape */
$secureRenderer->renderTag(
    tagName: 'script',
    attributes: [
        'type' => 'text/javascript',
        'id' => 'athoscommerce_tracking_cart_page',
    ],
    content: $scriptString,
    textContent: false,
) ?>
