<?php
declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \AthosCommerce\Feed\ViewModel\PdpViewModel $viewModel */
/** @var \AthosCommerce\Feed\ViewModel\GlobalScriptViewModel $scriptModel */

$viewModel = $block->getData('view_model');
$scriptModel = $block->getData('global_script_model');

if (!$scriptModel || !$viewModel || !$scriptModel->shouldRender()) {
    return;
}

$productPageData = $viewModel->getProductPageData();
if (!$productPageData) {
    return;
}
?>

<script type="text/javascript" id="athoscommerce_tracking_product_page">
    (function () {
        var productPageData = <?= /* @noEscape */ $productPageData ?>;

        window.athos.tracker.events.product = window.athos.tracker.events.product || {};

        if (typeof window.athos.tracker.events.product.pageView === 'function') {
            window.athos.tracker.events.product.pageView({
                data: {
                    result: {
                        uid: productPageData.uid,
                        sku: productPageData.sku,
                        parentId: productPageData.parentId,
                        price: productPageData.price,
                        currency: productPageData.currency
                    }
                }
            });
        }
    })();
</script>
